### ISSUE TITLE
Make the task run on all agent types

### ISSUE THREAD

**Issue by hferentschik** [hferentschik/openshift-vsts#43]
At the moment we only allow Linux agent to run the oc command execution task, but this can be extended to any agent type. Requiring Linux only just makes the download of the needed oc binary simpler.

**Comment by MagnusTim** [comment]
We are looking forward to try this.

**Comment by hferentschik** [comment]
Merged via pull request #54

**Comment by hferentschik** [comment]
Will be followed up by issue #50.
